apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: minerva-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Minerva deploys applications
  displayName: Minerva
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - deployment
  - minerva
  - ansible
  links:
  - name: Minerva Operator
    url: https://minerva-operator.domain
  maturity: alpha
  provider:
    name: Atarazana Inc.
    url: http://wikipedia.org/minerva
  version: 0.0.0
